# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 阿章的革命根据地
email: 1377699408@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  下定决心，不怕牺牲，排除万难，去争取胜利。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.azhangbaobao.cn" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: CheungChan137
github_username:  cheungchan

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-remote-theme

# theme: jekyll-text-theme
remote_theme: benbalter/retlab
text_skin: forest
highlight_theme: tomorrow-night-eighties #tomorrow-night-bright
lang: zh-CN
timezone: Asia/Shanghai
repository: cheungchan/iblog
excerpt_separator: <!--more-->
excerpt_type: html
# license: CC-BY-NC-4.0
toc:
  selectors: "h1,h2,h3,h4"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need
# Mathjax
mathjax: true
mathjax_autoNumber: true

# Mermaid
mermaid: true

# Chart
chart: true

comments:
  provider: valine
  valine:
    app_id  : "m1U7NfG0sjUkikIaevPIJowY-gzGzoHsz"
    app_key : "YoUgvxSNSoPmRUwNPyjL1q6I"
  placeholder: "来踩踩吧"
  lang: "zh-cn"
  notify: true
  visitor: true
  avatar: "monsterid"

# pageview:
#   provider: leancloud
#   leancloud:
#     app_id    : "4U8opX196aOmdRP9NXHz71u5-gzGzoHsz"
#     app_key   : "CTmWeRSov5qVG95hVN98RNiT"
#     app_class : "Test"
    
analytics:
  provider: google
  google:
    tracking_id: "UA-140963197-1"
    anonymize_ip: false
 # 对 css 和 js 资源的 cdn 加速配置
# cdn:
#   jsdelivr:
#     enabled: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
